"""
main_window.py — neurodash3 video viewer.

Receives a handoff directory from neurodash3 containing pre-serialized arrays
and metadata. Displays synchronized video, behavioral traces, LFP, and
spectrogram. No data loading or computation — just display.

Handoff directory contents:
    handoff.json        — metadata and display settings
    lfp.npz             — pre-normalized LFP traces (if has_neural)
    spectrogram.npz     — pre-computed spectrogram (if show_spectrogram)
"""

import json
import shutil
from pathlib import Path

import numpy as np
import imageio.v3 as iio
import av
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore
from PyQt6.QtWidgets import (
    QMainWindow, QWidget,
    QHBoxLayout, QVBoxLayout, QSlider, QLabel, QCheckBox, QSplitter,
    QDoubleSpinBox, QPushButton
)
from PyQt6.QtCore import Qt, QTimer

from neurodash3.plot_utils import velocity_ylim
from neurodash3.behavior_io import (
    load_behavior_file, get_recording_delay, estimate_position_pixels
)

# Spatial calibration defaults
# Generated by sandbox/pyqtdash_building/probe_calibration_matplotlib.py
# TODO: load per-arena calibration from ~/.neurodash/arenas/
_SCALE_X = 0.8002
_SCALE_Y = 1.0411
_OFFSET_X = 46.4
_OFFSET_Y = -22.9


# ---------------------------------------------------------------------------
# Data loading helpers
# ---------------------------------------------------------------------------

def _load_behavior(path):
    """Load EthoVision Excel file. Returns (data DataFrame, recording_delay_s)."""
    metadata, data = load_behavior_file(path)
    recording_delay_s = get_recording_delay(metadata)
    return data, recording_delay_s


def _estimate_position_pixels(x, y, video_width, video_height):
    """Map EthoVision cm to pixel coordinates using stored calibration."""
    return estimate_position_pixels(
        x, y, video_width, video_height,
        scale_x=_SCALE_X, scale_y=_SCALE_Y,
        offset_x=_OFFSET_X, offset_y=_OFFSET_Y,
    )


# ---------------------------------------------------------------------------
# Main window
# ---------------------------------------------------------------------------

class NeurodashViewer(QMainWindow):
    def __init__(self, handoff_dir: str):
        super().__init__()
        self.setWindowTitle("neurodash3 viewer")
        self._handoff_dir = handoff_dir

        # Load handoff metadata
        with open(Path(handoff_dir) / "handoff.json") as f:
            handoff = json.load(f)

        video_path = handoff.get("video_path") or None
        behavior_path = handoff.get("behavior_path")
        has_neural = handoff.get("has_neural", False)
        show_spectrogram = handoff.get("show_spectrogram", False)
        spectrogram_channel_name = handoff.get("spectrogram_channel_name")
        t_start = handoff.get("t_start", 0.0)
        window_duration = handoff.get("window_duration", 30.0)

        has_video = bool(video_path)
        has_behavior = behavior_path is not None

        # --- Load behavioral data ---
        if has_behavior:
            print("Loading behavioral data...")
            behavior, recording_delay_s = _load_behavior(behavior_path)
            self.t_behav = behavior["Recording time"].to_numpy(dtype=float)
            self.x_cm = behavior["X center"].to_numpy(dtype=float)
            self.y_cm = behavior["Y center"].to_numpy(dtype=float)
            self.velocity = behavior["Velocity"].to_numpy(dtype=float)
        else:
            recording_delay_s = 0.0

        # --- Load pre-serialized neural data ---
        if has_neural:
            print("Loading LFP from handoff...")
            lfp_data = np.load(Path(handoff_dir) / "lfp.npz", allow_pickle=True)
            self.t_neural = lfp_data["t"]
            self.lfp_traces = lfp_data["traces"]  # already normalized
            self.ch_names = list(lfp_data["channel_names"])
            self.lfp_y_range = tuple(lfp_data["y_range"])

            if show_spectrogram:
                print("Loading spectrogram from handoff...")
                spec_data = np.load(Path(handoff_dir) / "spectrogram.npz")
                self.freqs = spec_data["freqs"]
                self.spec_times = spec_data["times"]
                self.power_db = spec_data["power_db"]
        else:
            self.t_neural = self.t_behav if has_behavior else np.array([0.0])

        # --- Video metadata ---
        self.video_path = video_path
        if has_video:
            av_meta = iio.immeta(video_path, plugin="pyav")
            self.fps = av_meta.get("fps", 30.0)
            duration_s = av_meta.get("duration", None)
            total_frames = int(duration_s * self.fps) if duration_s else (len(self.t_behav) if has_behavior else 0)
            self.frame_offset = round(recording_delay_s * self.fps)
            self.n_frames = min(total_frames - self.frame_offset, len(self.t_behav) if has_behavior else total_frames)

            # Persistent decoder — open once and decode sequentially during
            # playback. The old reopen-and-seek-per-frame path capped playback
            # at ~7 fps; sequential decode restores real-time speed.
            self._container = av.open(video_path)
            self._video_stream = self._container.streams.video[0]
            self._video_stream.thread_type = "AUTO"
            self._decode_gen = None      # live sequential decode generator
            self._decode_next_idx = -1   # frame index the generator yields next
            self._img_levels = None      # display levels, fixed once from first frame
        else:
            self.fps = 30.0
            self.frame_offset = 0
            self.n_frames = len(self.t_behav) if has_behavior else (len(self.t_neural) if has_neural else 1)
            self._container = None

        if has_video and has_behavior:
            first_frame = self._read_video_frame(self.frame_offset)
            self.frame_h, self.frame_w = first_frame.shape[:2]
            self.px, self.py = _estimate_position_pixels(self.x_cm, self.y_cm, self.frame_w, self.frame_h)

        # --- Build UI ---
        central = QWidget()
        self.setCentralWidget(central)
        root = QVBoxLayout(central)
        root.setSpacing(4)

        self.main_splitter = QSplitter(Qt.Orientation.Vertical)
        root.addWidget(self.main_splitter)

        # Top: video | behavioral traces
        self.top_splitter = QSplitter(Qt.Orientation.Horizontal)
        self.main_splitter.addWidget(self.top_splitter)

        if has_video:
            self.image_view = pg.ImageView()
            self.image_view.ui.roiBtn.hide()
            self.image_view.ui.menuBtn.hide()
            self.image_view.ui.histogram.hide()
            self.top_splitter.addWidget(self.image_view)
            self.dot = pg.ScatterPlotItem(size=12, pen=pg.mkPen(None), brush=pg.mkBrush(255, 50, 50, 220))
            self.image_view.getView().addItem(self.dot)
        else:
            self.image_view = None
            self.dot = None

        if has_behavior:
            behav_panel = QWidget()
            behav_layout = QVBoxLayout(behav_panel)
            behav_layout.setSpacing(2)
            self.top_splitter.addWidget(behav_panel)
            self.top_splitter.setSizes([650, 550])

            pos_ymin = np.nanpercentile(np.concatenate([self.x_cm, self.y_cm]), 10)
            pos_ymax = np.nanpercentile(np.concatenate([self.x_cm, self.y_cm]), 90)
            _, vel_ymax = velocity_ylim(self.velocity)

            self.pos_plot = pg.PlotWidget(title="Position (cm)")
            self.pos_plot.addLegend(offset=(-1, 1), brush=pg.mkBrush(50, 50, 50, 200))
            self.pos_plot.plot(self.t_behav, self.x_cm, pen=pg.mkPen("c", width=1), name="X")
            self.pos_plot.plot(self.t_behav, self.y_cm, pen=pg.mkPen("m", width=1), name="Y")
            self.pos_plot.setYRange(pos_ymin, pos_ymax, padding=0.05)
            self.pos_cursor = pg.InfiniteLine(angle=90, pen=pg.mkPen("w", width=2))
            self.pos_plot.addItem(self.pos_cursor)
            behav_layout.addWidget(self.pos_plot)

            self.vel_plot = pg.PlotWidget(title="Velocity (cm/s)")
            self.vel_plot.plot(self.t_behav, self.velocity, pen=pg.mkPen("g", width=1))
            self.vel_plot.setYRange(0, vel_ymax, padding=0.05)
            self.vel_cursor = pg.InfiniteLine(angle=90, pen=pg.mkPen("w", width=2))
            self.vel_plot.addItem(self.vel_cursor)
            behav_layout.addWidget(self.vel_plot)

        # Slider row
        slider_row = QWidget()
        slider_layout = QVBoxLayout(slider_row)
        root.addWidget(slider_row)

        slider_controls = QWidget()
        slider_controls_layout = QHBoxLayout(slider_controls)
        slider_controls_layout.setContentsMargins(0, 0, 0, 0)
        slider_layout.addWidget(slider_controls)

        left = QWidget()
        left_layout = QVBoxLayout(left)
        left_layout.setContentsMargins(0, 0, 0, 0)
        left_layout.setSpacing(2)

        self.time_label = QLabel("t = 0.00 s  |  frame 0")
        self.time_label.setAlignment(Qt.AlignmentFlag.AlignLeft)
        left_layout.addWidget(self.time_label)

        # Transport row: play/pause button + scrub slider
        transport = QWidget()
        transport_layout = QHBoxLayout(transport)
        transport_layout.setContentsMargins(0, 0, 0, 0)

        self.play_button = QPushButton("▶ Play")
        self.play_button.setCheckable(True)
        self.play_button.clicked.connect(self.on_play_clicked)
        transport_layout.addWidget(self.play_button)

        self.slider = QSlider(Qt.Orientation.Horizontal)
        self.slider.setMinimum(0)
        self.slider.setMaximum(self.n_frames - 1)
        self.slider.setValue(0)
        self.slider.valueChanged.connect(self.on_slider_changed)
        transport_layout.addWidget(self.slider, stretch=1)

        left_layout.addWidget(transport)
        slider_controls_layout.addWidget(left, stretch=1)

        # Playback timer — advances one frame per tick at real-time fps.
        # PreciseTimer keeps tick spacing near the true 33 ms on Windows, where
        # the default coarse timer snaps to ~15.6 ms and staggers playback.
        self.play_timer = QTimer(self)
        self.play_timer.setTimerType(Qt.TimerType.PreciseTimer)
        self.play_timer.timeout.connect(self._advance_frame)
        self._play_interval_ms = max(1, round(1000 / self.fps))

        right = QWidget()
        right_layout = QVBoxLayout(right)
        right_layout.setContentsMargins(0, 0, 0, 0)
        right_layout.setSpacing(2)

        controls_row = QWidget()
        controls_row_layout = QHBoxLayout(controls_row)
        controls_row_layout.setContentsMargins(0, 0, 0, 0)
        controls_row_layout.addWidget(QLabel("Window (s):"))
        self.window_spinbox = QDoubleSpinBox()
        self.window_spinbox.setMinimum(1.0)
        self.window_spinbox.setMaximum(300.0)
        self.window_spinbox.setSingleStep(5.0)
        self.window_spinbox.setValue(window_duration)
        self.window_spinbox.valueChanged.connect(self.on_window_duration_changed)
        controls_row_layout.addWidget(self.window_spinbox)
        self.zoom_checkbox = QCheckBox("Zoom")
        self.zoom_checkbox.setChecked(True)
        self.zoom_checkbox.stateChanged.connect(self.on_zoom_mode_changed)
        controls_row_layout.addWidget(self.zoom_checkbox)
        right_layout.addWidget(controls_row)
        slider_controls_layout.addWidget(right)

        # LFP
        if has_neural:
            colors = ["c", "m", "y"]
            self.lfp_plot = pg.PlotWidget(title="LFP")
            self.lfp_plot.setLabel("left", "Amplitude (mV)")
            self.lfp_plot.setLabel("bottom", "Time (s)")
            self.lfp_plot.addLegend(offset=(-1, 1), brush=pg.mkBrush(50, 50, 50, 200))

            for i, trace in enumerate(self.lfp_traces):
                name = self.ch_names[i] if i < len(self.ch_names) else f"Ch {i+1}"
                color = colors[i % len(colors)]
                self.lfp_plot.plot(self.t_neural, trace, pen=pg.mkPen(color, width=1), name=name)

            self.lfp_cursor = pg.InfiniteLine(angle=90, pen=pg.mkPen("w", width=2))
            self.lfp_plot.addItem(self.lfp_cursor)
            self.lfp_plot.getAxis("left").setTicks([])
            self.lfp_plot.setYRange(*self.lfp_y_range, padding=0)
            self.main_splitter.addWidget(self.lfp_plot)

        # Spectrogram (only if Dash had it enabled)
        if show_spectrogram:
            spec_title = f"Spectrogram — {spectrogram_channel_name}" if spectrogram_channel_name else "Spectrogram"
            self.spec_plot = pg.PlotWidget(title=spec_title)
            self.spec_plot.setLabel("left", "Frequency (Hz)")
            self.spec_plot.setLabel("bottom", "Time (s)")

            img = pg.ImageItem()
            img.setImage(self.power_db.T)
            img.setRect(QtCore.QRectF(
                self.spec_times[0], self.freqs[0],
                self.spec_times[-1] - self.spec_times[0],
                self.freqs[-1] - self.freqs[0]
            ))
            img.setColorMap(pg.colormap.get("inferno"))
            self.spec_plot.addItem(img)

            self.spec_cursor = pg.InfiniteLine(angle=90, pen=pg.mkPen("w", width=2))
            self.spec_plot.addItem(self.spec_cursor)
            self.spec_plot.setYRange(0, self.freqs[-1], padding=0)
            self.main_splitter.addWidget(self.spec_plot)

        # Set splitter sizes based on what's shown
        if has_neural and show_spectrogram:
            self.main_splitter.setSizes([500, 200, 200])
        elif has_neural:
            self.main_splitter.setSizes([500, 200])

        # Collect all time-series plots for range updates
        self._time_plots = []
        if has_behavior:
            self._time_plots += [self.pos_plot, self.vel_plot]
        if has_neural:
            self._time_plots.append(self.lfp_plot)
        if show_spectrogram:
            self._time_plots.append(self.spec_plot)

        for plot in self._time_plots:
            plot.enableAutoRange(x=False, y=False)
            plot.setXRange(0, window_duration, padding=0)

        self._has_video = has_video
        self._has_behavior = has_behavior
        self._has_neural = has_neural
        self._show_spectrogram = show_spectrogram

        # Seek to t_start
        if has_behavior:
            initial_idx = int(np.searchsorted(self.t_behav, t_start))
        else:
            initial_idx = int(round(t_start * self.fps))
        initial_idx = max(0, min(initial_idx, self.n_frames - 1))
        self.slider.setValue(initial_idx)

        self.resize(1400, 900)
        print("Ready.")
        QTimer.singleShot(100, lambda: self.show_frame(initial_idx))

    def _read_video_frame(self, video_idx):
        """Return the RGB frame (H, W, 3) at video_idx.

        Fast path: if video_idx continues the current decode sequence
        (playback), pull the next decoded frame. Slow path: on a jump/scrub,
        seek to the nearest keyframe and decode forward to the exact frame.
        """
        if self._decode_gen is not None and video_idx == self._decode_next_idx:
            frame = next(self._decode_gen, None)
            if frame is not None:
                self._decode_next_idx += 1
                return frame.to_ndarray(format="rgb24")

        stream = self._video_stream
        start_ts = stream.start_time or 0
        target_pts = int(round(video_idx / self.fps / stream.time_base)) + start_ts
        self._container.seek(target_pts, stream=stream, backward=True, any_frame=False)
        self._decode_gen = self._container.decode(stream)
        for frame in self._decode_gen:
            fidx = int(round((frame.pts - start_ts) * stream.time_base * self.fps))
            if fidx >= video_idx:
                self._decode_next_idx = fidx + 1
                return frame.to_ndarray(format="rgb24")
        return None  # past end of video

    def show_frame(self, behavior_idx):
        if self._has_video:
            video_idx = behavior_idx + self.frame_offset
            frame = self._read_video_frame(video_idx)
            if frame is not None:
                if self._img_levels is None:
                    self._img_levels = (float(frame.min()), float(frame.max()))
                self.image_view.setImage(
                    frame.transpose(1, 0, 2),
                    autoLevels=False, autoRange=False, levels=self._img_levels,
                )

        if self._has_behavior:
            t = self.t_behav[min(behavior_idx, len(self.t_behav) - 1)]
            if self._has_video and self.dot is not None:
                idx = min(behavior_idx, len(self.px) - 1)
                self.dot.setData([self.px[idx]], [self.py[idx]])
            self.pos_cursor.setValue(t)
            self.vel_cursor.setValue(t)
        else:
            t = behavior_idx / self.fps

        self.time_label.setText(f"t = {t:.2f} s  |  frame {behavior_idx}")

        if self._has_neural:
            self.lfp_cursor.setValue(t)
        if self._show_spectrogram:
            self.spec_cursor.setValue(t)

        if self.zoom_checkbox.isChecked():
            window = self.window_spinbox.value()
            half = window / 2
            x_left = max(0.0, t - half)
            x_right = x_left + window
            for plot in self._time_plots:
                plot.setXRange(x_left, x_right, padding=0)

    def on_window_duration_changed(self):
        if self.zoom_checkbox.isChecked():
            self.show_frame(self.slider.value())

    def on_zoom_mode_changed(self):
        if not self.zoom_checkbox.isChecked():
            t_max = max(
                self.t_behav[-1] if self._has_behavior else 0,
                self.t_neural[-1] if self._has_neural else 0
            )
            for plot in self._time_plots:
                plot.setXRange(0, t_max, padding=0.02)
        else:
            self.show_frame(self.slider.value())

    def on_slider_changed(self, behavior_idx):
        self.show_frame(behavior_idx)

    def on_play_clicked(self, checked):
        if checked:
            self._start_playback()
        else:
            self._stop_playback()

    def _start_playback(self):
        # Restart from the beginning if we're parked at the last frame
        if self.slider.value() >= self.slider.maximum():
            self.slider.setValue(0)
        self.play_button.setChecked(True)
        self.play_button.setText("⏸ Pause")
        self.play_timer.start(self._play_interval_ms)

    def _stop_playback(self):
        self.play_timer.stop()
        self.play_button.setChecked(False)
        self.play_button.setText("▶ Play")

    def _advance_frame(self):
        idx = self.slider.value()
        if idx >= self.slider.maximum():
            self._stop_playback()
            return
        self.slider.setValue(idx + 1)  # fires on_slider_changed -> show_frame

    def closeEvent(self, event):
        """Clean up handoff directory on close."""
        self.play_timer.stop()
        if self._container is not None:
            self._container.close()
        if self._handoff_dir and Path(self._handoff_dir).exists():
            shutil.rmtree(self._handoff_dir, ignore_errors=True)
        super().closeEvent(event)
